# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-24 04:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='e_mail',
            new_name='email',
        ),
    ]
