# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-23 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desc',
            name='courses',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Desc',
        ),
    ]
