# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-20 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(related_name='authors', to='book_authors.Book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='desc',
            field=models.TextField(max_length=1000),
        ),
    ]
