# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-20 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors', '0002_auto_20170820_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default='DEFAULT VIEW'),
        ),
    ]
